### ISSUE TITLE
小小的提个建议

### ISSUE THREAD

**Issue by ghost** [taoche/Vue-date-picker#2]
试用了一下, 有个小特性使我感到有些难受.就是切换月份的按钮会在日历框大小改变后变动位置.使我难以流畅的点下去.如果把锚点放在那一行上是不是会更好一些呢

**Comment by taoche** [comment]
感谢你的建议，这个问题我之前就发现了。 很快就会修复这个 bug。
Thanks!

**Comment by taoche** [comment]
已经调整了这个问题，但是方式不是很好，我还在想更好的解决办法。谢谢你的建议。
